### ISSUE TITLE
Mapping is incorrect

### ISSUE THREAD

**Issue by alterhuman** [Coronon/flutter_octicons#2]
For example, OctIcons.home_fill_16 renders italics icon.

**Comment by Coronon** [comment]
Thats weird... All the code is auto-generated so something underlying probably changed. I'm a little short on time right now, but will look into this :)

**Comment by JohnathanHill** [comment]
> For example, OctIcons.home_fill_16 renders italics icon.

Same issue here

**Comment by JHubi1** [comment]
Yeah, same issue here,
- `OctIcons.accessibility_24` renders a calendar icon
- `OctIcons.star_fill_24` a block icon
- And so on
The icons aren't mapped correctly. May you fix that? I would really need this package, thanks

**Comment by JHubi1** [comment]
I did some research and the last working version was `0.5.0`. That one was fully working (as far as I can tell). `0.6.0` already shifts the icons around. You really need to fix this, it's a serious issue, that deems the package unusable, and that has been around for 38 (!) versions

Edit: ok, nvm, `0.2.0` is the last working version for most of the icons

**Comment by Coronon** [comment]
It seems the order of the glyphs in the font files was changed from alphabetical to reverse alphabetical somewhere down the line. Should be fixed with 69f62cddac1db16fcae451810f90dfbcc877f155 and version [`1.45.0`](https://pub.dev/packages/flutter_octicons/versions/1.45.0). I also added an example project for quicker debugging in the future :)
